---
site_name: AppSec Course
site_url: "https://course.geminishkv.tech/"
site_description: >
  Практический курс по прикладной безопасности приложений: лабораторные работы и аннотационные материалы
  для прокачки навыков в ИБ (информационной безопасности), а также чеклисты и методички по AppSec, DevSecOps
  и OWASP Top 10.
site_author: "Илья Шмаков"
repo_url: https://github.com/geminishkv/course_labs
repo_name: geminishkv/course_labs
edit_uri: edit/develop/docs/

theme:
  name: material
  language: ru
  logo: artifacts/assets/logo.svg
  icon:
    menu: fontawesome/solid/bars-staggered
    top: fontawesome/solid/angles-up
    down: fontawesome/solid/angles-down
    previous: fontawesome/solid/angles-left
    next: fontawesome/solid/angles-right
    close: fontawesome/solid/xmark
  favicon: artifacts/assets/favicon.ico
  font: false
  features:
    - navigation.indexes
    - search.highlight
    - navigation.tabs.sticky
    - navigation.top
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.view
    - navigation.instant
    - navigation.instant.prefetch
    - toc.follow
    - toc.integrate

plugins:
  - search
  - meta-descriptions
  - macros
  - mkdocs-pdf
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
  - include-markdown:
      heading_offset: 0
      preserve_includer_indent: false
      dedent: true

markdown_extensions:
  - def_list
  - md_in_html
  - attr_list
  - fenced_code
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      pygments_style: monokai
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - toc:
      permalink: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols

watch:
  - docs

extra_css:
  - stylesheets/fonts.css
  - stylesheets/header.css
  - stylesheets/footer.css
  - stylesheets/search.css
  - stylesheets/sidebar.css
  - stylesheets/typeset.css
  - stylesheets/tools-overlay.css
  - stylesheets/burger.css
  - stylesheets/mobile-logo.css
  - stylesheets/layout.css
  - stylesheets/clipboard.css

extra_javascript:
  - javascripts/custom-title.js
  - javascripts/typewriter-target.js
  - javascripts/home-toc.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geminishkv
    - icon: fontawesome/solid/code-branch
      link: https://github.com/geminishkv/course_labs
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/geminishkvdev
    - icon: fontawesome/brands/telegram
      link: https://t.me/shmakovis_appsec
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/geminishkv
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/geminishkvdev
    - icon: fontawesome/regular/envelope-open
      link: mailto:shmakovis@inbox.ru
    - icon: fontawesome/solid/rss
      link: https://geminishkv.github.io/course_labs/feed.xml
#  analytics:
#    provider: google
#    property: G-XXXXXXXXXX

nav:
  - "geminishkv.tech": "https://geminishkv.tech/"
  - "Главная страница": index.md
  - "Лабораторные работы":
      - "Лабораторная работа №1": labs/lab01.md
      - "Лабораторная работа №2": labs/lab02.md
      - "Лабораторная работа №3": labs/lab03.md
      - "Лабораторная работа №4": labs/lab04.md
      - "Лабораторная работа №5": labs/lab05.md
      - "Лабораторная работа №6": labs/lab06.md
      - "Лабораторная работа №7": labs/lab07.md
      - "Лабораторная работа №8": labs/lab08.md
      - "Лабораторная работа №9": labs/lab09.md
      - "Лабораторная работа №10": labs/lab10.md
      - "pet_project": labs/pet_project.md
  - "Тесты":
      - "Тест №1": tests/test01.md
      - "Тест №2": tests/test02.md
      - "Тест №3": tests/test03.md
      - "Тест №4": tests/test04.md
      - "Тест №5": tests/test05.md
  - "Материалы":
      - "Примеры":
          - "Аналитические кейсы": materials/examples/exmpl.md
          - "Использование MultiSiq": materials/examples/Multisignature.md
          - "PrintNightmare": materials/examples/PrintNightmare.md
          - "Risk Analysis": materials/examples/RA.md
      - "Лицензии ПО": licenses.md
      - "Классификация инструментов": appsec_tt.md
      - "OWASP TOP 10":
          - "CI/CD Risks": materials/OWASPTOP10/OWASP_Top_10_CICD_Risks.md
          - "Authorization": materials/OWASPTOP10/Authorization.md
          - "Authentication": materials/OWASPTOP10/Authentication.md
          - "Client-side Attacks": materials/OWASPTOP10/client-side-attacks.md
          - "Command Execution": materials/OWASPTOP10/command-execution.md
          - "Logical Attacks": materials/OWASPTOP10/logical-attacks.md
          - "Information Disclosure": materials/OWASPTOP10/information-disclosure.md
      - "CheatSheet":
          - "GitHub CLI": artifacts/cheatsheet/CHEATSHEET_GH_CLI.md
          - "GitSCM": artifacts/cheatsheet/CHEATSHEET_GIT.md
          - "Docker": artifacts/cheatsheet/CHEATSHEET_DOCKER.md
          - ".dockerignore": artifacts/cheatsheet/CHEATSHEET_DOCKERIGNORE.md
          - ".gitignore": artifacts/cheatsheet/CHEATSHEET_GITIGNORE.md
      - "Приложение": APPENDIX.md
  - "О проекте": about.md
  - "Релизы": RELEASE_NOTES.md
  - "Политика безопасности": Security.md
  - "Application Security Toolchain Map": "https://geminishkv.github.io/oss_toolchainmap/"
  - "FinDevSecOps": "https://findevsecops.ru/"
  - "АО ЛАНИТ": "https://www.lanit.ru"
